/**
 * 该文件由脚本自动生成，如需修改请联系 PMC
 * This file generated by scripts of tdesign-api. `npm run api:docs Divider React(PC) vitest,finalProject`
 * If you need to modify this file, contact PMC first please.
 */
import React from 'react';
import { render } from '@test/utils';
import Divider from '..';

describe('Divider Component', () => {
  ['left', 'right', 'center'].forEach((item) => {
    it(`props.align is equal to ${item}`, () => {
      const { container } = render(<Divider align={item}>Text</Divider>);
      expect(container.firstChild).toHaveClass(`t-divider--with-text-${item}`);
      expect(container).toMatchSnapshot();
    });
  });

  it('props.content works fine', () => {
    const { container } = render(<Divider content={<span className="custom-node">TNode</span>}></Divider>);
    expect(container.querySelector('.custom-node')).toBeTruthy();
    expect(container).toMatchSnapshot();
  });

  it('props.dashed works fine', () => {
    const { container: container1 } = render(<Divider>Text</Divider>);
    expect(container1.querySelector('.t-divider--dashed')).toBeFalsy();
    const { container: container2 } = render(<Divider dashed={true}>Text</Divider>);
    expect(container2.firstChild).toHaveClass('t-divider--dashed');
  });

  ['horizontal', 'vertical'].forEach((item) => {
    it(`props.layout is equal to ${item}`, () => {
      const { container } = render(<Divider layout={item}>Text</Divider>);
      expect(container.firstChild).toHaveClass(`t-divider--${item}`);
      expect(container).toMatchSnapshot();
    });
  });
});
