/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * 该文件由脚本自动生成，如需修改请联系 PMC
 * This file generated by scripts of tdesign-api. `npm run api:docs Space React(PC) vitest,finalProject`
 * If you need to modify this file, contact PMC first please.
 */
import React from 'react';
import { Space } from '..';
import { getSpaceDefaultMount } from './mount';

describe('Space Component', () => {
  ['start', 'end', 'center', 'baseline'].forEach((item) => {
    it(`props.align is equal to ${item}`, () => {
      const { container } = getSpaceDefaultMount(Space, { align: item });
      expect(container.firstChild).toHaveClass(`t-space-align-${item}`);
    });
  });

  it('props.breakLine works fine', () => {
    // breakLine default value is false
    const { container: container1 } = getSpaceDefaultMount(Space);
    expect(container1.querySelector(`.${'t-space--break-line'}`)).toBeFalsy();
    // breakLine = true
    const { container: container2 } = getSpaceDefaultMount(Space, { breakLine: true });
    expect(container2.firstChild).toHaveClass('t-space--break-line');
    // breakLine = false
    const { container: container3 } = getSpaceDefaultMount(Space, { breakLine: false });
    expect(container3.querySelector(`.${'t-space--break-line'}`)).toBeFalsy();
  });

  ['vertical', 'horizontal'].forEach((item) => {
    it(`props.direction is equal to ${item}`, () => {
      const { container } = getSpaceDefaultMount(Space, { direction: item });
      expect(container.firstChild).toHaveClass(`t-space-${item}`);
    });
  });

  it('props.separator works fine', () => {
    const { container } = getSpaceDefaultMount(Space, { separator: <span className="custom-node">TNode</span> });
    expect(container.querySelector('.custom-node')).toBeTruthy();
  });

  it(`props.size is equal to 'small'`, () => {
    const { container } = getSpaceDefaultMount(Space, { size: 'small' });
    const domWrapper = container.firstChild;
    expect(domWrapper.style.gap).toBe('8px');
  });
  it(`props.size is equal to 'large'`, () => {
    const { container } = getSpaceDefaultMount(Space, { size: 'large' });
    const domWrapper = container.firstChild;
    expect(domWrapper.style.gap).toBe('24px');
  });
  it(`props.size is equal to '38px'`, () => {
    const { container } = getSpaceDefaultMount(Space, { size: '38px' });
    const domWrapper = container.firstChild;
    expect(domWrapper.style.gap).toBe('38px');
  });
  it(`props.size is equal to ['20px', '80px']`, () => {
    const { container } = getSpaceDefaultMount(Space, { size: ['20px', '80px'] });
    const domWrapper = container.firstChild;
    expect(domWrapper.style.gap).toBe('20px 80px');
  });
});
