name: Publish_Any_Commit
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    if: ${{ github.repository == 'Tencent/tdesign-react' && !startsWith(github.head_ref, 'release/')}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v4 

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: pnpm install

      - run: pnpm exec run-p build build:aigc

      - run: |
          mkdir templates && cd templates
          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main react-vite --template react-vite

          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main react-rspack --template react-rspack

          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main react-vike --template react-vike

          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main react-chat-vite --template react-chat-vite

          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main react-chat-rspack --template react-chat-rspack

          pnpm dlx https://pkg.pr.new/TDesignOteam/create-tdesign@main react-chat-vike --template react-chat-vik

      - run: pnpm dlx pkg-pr-new publish './packages/*' --template './templates/*'
